# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TADO Sec

on:
  push:
    # Only trigger if files in this path changed
    paths:
      - 'tado-sec/my-react-app/**'
      - '.github/workflows/tado.sec.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]
  pull_request:
    # Only trigger if files in this path changed
    paths:
      - 'tado-sec/my-react-app/**'
      - '.github/workflows/tado.sec.yml'
      # Don't run on Markdown changes
      - '!**.md'
    branches: [ main ]

jobs:
  build:

    name: test-${{matrix.os}}-${{matrix.node-version}}
    strategy:
      #fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest]
        node-version: [14.x, 16.x]
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        working-directory: ./tado-sec/my-react-app/
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Build the app 🏗
      run: npm run build
    - name: Start the app 📤
      run: |
        npm start &
        npx wait-on --timeout 60000
      # it's very useful to have extra logging in a ci execution
    - run: npm run test.sanity.ci
