version: '3'
services:
  selenium-hub:
    container_name: selenium-hub
    restart: always
    image: selenium/hub:3.141.59-xenon
    volumes:
    - /dev/shm:/dev/shm
    environment:
    - GRID_TIMEOUT=30000
    - GRID_MAX_SESSION=30
    ports:
      - "4444:4444"

  selenium-node-chrome:
    container_name: selenium-node-chrome
    restart: always
    image: selenium/node-chrome-debug:3.141.59-xenon
    stdin_open: true
    volumes:
    - /dev/shm:/dev/shm
    ports:
      - "5901:5900"
    depends_on:
      - 'selenium-hub' 
    environment:
    - HUB_HOST=selenium-hub
    - NODE_MAX_INSTANCES=30
    - NODE_MAX_SESSION=30
    - SCREEN_HEIGHT=1080
    - SCREEN_WIDTH=1920
    
  selenium-node-firefox:
    container_name: selenium-node-firefox
    restart: always
    image: selenium/node-firefox-debug:3.141.59
    stdin_open: true
    volumes:
    - /dev/shm:/dev/shm
    ports:
      - "5902:5900"
    depends_on:
      - 'selenium-hub' 
    environment:
    - HUB_HOST=selenium-hub
    - NODE_MAX_INSTANCES=30
    - NODE_MAX_SESSION=30
    - SCREEN_HEIGHT=1080
    - SCREEN_WIDTH=1920
